### ISSUE TITLE
WiFi fails on booting IoT WoT example on Artik053 board.

### ISSUE THREAD

**Issue by nherriot** [rzr/webthing-iotjs#1]
TASH>>reboot�

U-Boot 2017.01-g59977f7 (Nov 23 2017 - 16:09:49 +0900)

CPU:   Exynos200 @ 320 MHz
Model: ARTIK-053 based on Exynos T20
DRAM:  946 KiB
WARNING: Caches not enabled
BL1 released at 2017-3-13 15:00
SSS released at 2017-09-12
WLAN released at 2017-11-30
Flash: 8 MiB
*** Warning - bad CRC, using default environment

In:    serial@80180000
Out:   serial@80180000
Err:   serial@80180000
Hit any key to stop autoboot:  0 
gpio: pin gpg16 (gpio 46) value is 1
## Starting application at 0x040Cx020 ...
s5j_sflash_init: FLASH Quad Enabled
uart_register: Registering /dev/console
uart_register: Registering /dev/ttyS0
uart_register: Registering /dev/ttyS1
uart_register: Registering /dev/ttyS2
uart_register: Registering /dev/ttyS3
uart_register: Registering /dev/ttyS4
System Information:
        Version: 2.0
        Commit Hash: 24efd30d608ffe2e322caa9d2c0a3a926c26b590
        Build User: nherriot@Zenbook-UX32A
        Build Time: 2018-10-09 14:27:28
        System Time: 01 Jan 2010, 00:00:00 [s] UTC Hardware RTC Support
TASH>>log: iotjs_startup_wifi_connect
log: Connecting to SSID "public" (0+0)
log: Wait (1/3) sec...
i2c_uioregister: Registering /dev/i2c-0
i2c_uioregister: Registering /dev/i2c-1
log: Wait (2/3) sec...
ASH: length of input character is too long, maximum length is 128
TASH>>B _handle_request:1334 state(0) evt(0)
[WM] T7 _handler_on_uninitialized_state:887 state(0) evt(0)
Starting supplicant in foreground...
1262304003.123427: Successfully initialized wpa_supplicant
1262304006.206938: wl1: callling L2_packet_init: 
1262304006.206938: wl1: Own MAC address: 28:6d:97:40:15:96
[WM] T7 <-- _handle_request
[WM] T7 _handle_request:1334 state(1) evt(4)
[WM] T7 _handler_on_disconnected_state:943 state(1) evt(4)
[WM] T7 _wifimgr_connect_ap:744
connect ap fail
[WM] T7 <-- _handle_request
error: wifi_manager_connect_ap (status=0xffffffff)
TASH: length of input character is too long, maximum length is 128
TASH>>[B

**Comment by rzr** [comment]
Thx for reporting this issue

Please rebuild branch "sandbox/rzr/devel/artik/053/master" and then flash and reboot and then copy the full log

Anyway what I see here, is a failure to connect to default "public" AP:
```
connect ap fail
```
But this error should not be printed, this is misleading:
```
TASH: length of input character is too long, maximum length is 128
```

I guess this should be fixed in TizenRT, This should be investigated more.

Meanwhile I will verify instructions at:
https://github.com/rzr/webthing-iotjs/wiki/TizenRT

**Comment by nherriot** [comment]
I get this from my cutecom window (with scroll bar!)


U-Boot 2017.01-g59977f7 (Nov 23 2017 - 16:09:49 +0900)

CPU:   Exynos200 @ 320 MHz
Model: ARTIK-053 based on Exynos T20
DRAM:  946 KiB
WARNING: Caches not enabled
BL1 released at 2017-3-13 15:00
SSS released at 2017-09-12
WLAN released at 2017-11-30
Flash: 8 MiB
*** Warning - bad CRC, using default environment

In:    serial@80180000
Out:   serial@80180000
Err:   serial@80180000
Hit any key to stop autoboot:  0 
gpio: pin gpg16 (gpio 46) value is 1
## Starting application at 0x040C\0xb8020 ...
s5j_sflash_init: FLASH Quad Enabled
uart_register: Registering /dev/console
uart_register: Registering /dev/ttyS0
uart_register: Registering /dev/ttyS1
uart_register: Registering /dev/ttyS2
uart_register: Registering /dev/ttyS3
uart_register: Registering /dev/ttyS4
System Information:
\0x09Version: 2.0
\0x09Commit Hash: eec74f072c1dd16c9713862850bc5ff3393e5209
\0x09Build User: nherriot@Zenbook-UX32A
\0x09Build Time: 2018-10-09 15:53:51
\0x09System Time: 01 Jan 2010, 00:00:00 [s] UTC Hardware RTC Support
TASH>>\0x00log: iotjs_startup_wifi_connect
log: Connecting to SSID "srbackup" (4+5)
log: Wait (1/3) sec...
i2c_uioregister: Registering /dev/i2c-0
i2c_uioregister: Registering /dev/i2c-1
log: Wait (2/3) sec...
log: Wait (3/3) sec...
[WM] T7 _handle_request:1334 state(0) evt(0)
[WM] T7 _handler_on_uninitialized_state:887 state(0) evt(0)
Starting supplicant in foreground...
1262304003.123427: Successfully initialized wpa_supplicant
1262304006.206938: wl1: callling L2_packet_init: 
1262304006.206938: wl1: Own MAC address: 28:6d:97:40:15:96
[WM] T7 <-- _handle_request
[WM] T7 _handle_request:1334 state(1) evt(4)
[WM] T7 _handler_on_disconnected_state:943 state(1) evt(4)
[WM] T7\0x09_wifimgr_connect_ap:744
[WM] T7\0x09_wifimgr_save_connected_config:733
[WM] T7 <-- _handle_request
1262304008.122906: wl1: Associated with 0c:68:03:ca:46:e7
1262304008.142864: wl1: WPA: Key negotiation completed with 0c:68:03:ca:46:e7 [PTK=CCMP GTK=CCMP]
1262304008.152843: wl1: CTRL-EVENT-CONNECTED 
[WM] T12\0x09_wifi_utils_connect_event:834
[WM] T12 _handle_request:1334 state(3) evt(9)
[WM] T12 _handler_on_connecting_state:1011 state(3) evt(9)
[WM] IP address : 192.168.110.197 ----
[WM] T12\0x09_handle_user_cb:1269
[WM] call sta connect success event
log: iotjs_startup_wifi_sta_connected status=0x0
[WM] T12 <-- _handle_request
log: IoT.js app: Starting:
{
  "env": {
    "HOME": "",
    "IOTJS_PATH": "/rom",
    "IOTJS_ENV": "",
    "IOTJS_EXTRA_MODULE_PATH": "",
    "IOTJS_WORKING_DIR_PATH": ""
  },
  "builtin_modules": {
    "adc": true,
    "assert": true,
    "buffer": true,
    "console": true,
    "dgram": true,
    "dns": true,
    "events": true,
    "fs": true,
    "gpio": true,
    "http": true,
    "http_client": true,
    "http_common": true,
    "http_incoming": true,
    "http_outgoing": true,
    "http_server": true,
    "https": true,
    "i2c": true,
    "iotjs": true,
    "module": true,
    "net": true,
    "pwm": true,
    "spi": true,
    "stream": true,
    "stream_duplex": true,
    "stream_internal": true,
    "stream_readable": true,
    "stream_writable": true,
    "timers": true,
    "tls": true,
    "uart": true,
    "util": true,
    "constants": true,
    "http_parser": true,
    "process": true,
    "tcp": true,
    "udp": true
  },
  "platform": "tizenrt",
  "arch": "arm",
  "version": "1.0.0",
  "iotjs": {
    "board": "artik05x"
  },
  "argv": [
    "iotjs",
    "/rom/example/index.js"
  ],
  "_events": {},
  "exitCode": 0,
  "_exiting": false
}
log: IoT.js app: Loading: /rom/iotjs-modules/webthing-iotjs/example/platform/index.js
log: board: artik05x: Loading
Usage:
iotjs /rom/example/index.js [board] [port]
Try:
curl -H "Accept: application/json" http://localhost:8888

log: board: artik05x: Started
log: GPIO: BlueLed: open: null
log: GPIO: RedLed: open: null
log: GPIO: LeftButton: open: null (null expected)
log: GPIO: RightButton: open: null (null expected)
log: ADC: ADC1: open: null (null expected)
log: ADC: ADC2: open: null (null expected)
log: GPIO: LeftButton: change: true
log: GPIO: RightButton: change: true
log: ADC: ADC1: change: 0%
log: ADC: ADC2: change: 0%

**Comment by rzr** [comment]
Feel free to create a bug on TizenRT repo about the missleading error a link to it
then we can close this bug because you seems to be able to configure wifi now, maybe we can improve this by reading a cred file on fs but it will be less secure ?

**Comment by nherriot** [comment]
Further to this log output. I still get locking after some time, I did notice an error log come up just before it locks. If I get time today I'll paste here. Trouble is I've totally blown my time budget and now fully focused on getting all other parts of the system ready to ship - so the TizenRT part of the demo will not be shown.
If you are available Sat/Sun I'll have another attempt.

**Comment by rzr** [comment]
For reference here is my log (on 055s) of updated branch:

```sh
    git clone --depth 1 -b sandbox/rzr/webthing/master https://github.com/TizenTeam/TizenRT ; cd TizenRT 
    make machine=artik053s menuconfig demo
```

```
TASH>>reboot�

U-Boot 2017.01-g59977f7 (Nov 23 2017 - 16:09:52 +0900)

CPU:   Exynos200 @ 320 MHz
Model: ARTIK-053 based on Exynos T20
DRAM:  946 KiB
WARNING: Caches not enabled
BL1 released at 2017-3-13 15:00
SSS released at 2017-09-12
WLAN released at 2017-03-21
Flash: 8 MiB
*** Warning - bad CRC, using default environment

In:    serial@80180000
Out:   serial@80180000
Err:   serial@80180000
Hit any key to stop autoboot:  0
gpio: pin gpg16 (gpio 46) value is 1
## Starting application at 0x040C�020 ...
s5j_sflash_init: FLASH Quad Enabled
i2c_uioregister: Registering /dev/i2c-0
i2c_uioregister: Registering /dev/i2c-1
System Information:
        Version: 2.0
        Commit Hash: 827eb273afdf7b8b9353b94c486335177495e0e3
        Build User: philippe@wsf1127
        Build Time: 2018-10-18 16:21:40
        System Time: 07 Feb 2106, 06:28:15 [s] UTC Hardware RTC Support
TASH>>log: iotjs_startup_wifi_connect
log: Connecting to SSID "@TizenHelper" (4+5)
log: Wait (1/3) sec...
log: Wait (2/3) sec...
log: Wait (3/3) sec...
[WM] T6 _handle_request:1334 state(0) evt(0)
[WM] T6 _handler_on_uninitialized_state:887 state(0) evt(0)
Starting supplicant in foreground...
3.061453: Successfully initialized wpa_supplicant
6.144964: wl1: callling L2_packet_init: 
6.144964: wl1: Own MAC address: 28:6d:FF:FF:FF:FF
[WM] T6 <-- _handle_request
[WM] T6 _handle_request:1334 state(1) evt(4)
[WM] T6 _handler_on_disconnected_state:943 state(1) evt(4)
[WM] T6 _wifimgr_connect_ap:744
[WM] T6 _wifimgr_save_connected_config:733
[WM] T6 <-- _handle_request
8.080890: wl1: Associated with a4:2b:FF:FF:FF:FF
8.090869: wl1: WPA: Key negotiation completed with a4:2b:FF:FF:FF:FF [PTK=CCMP GTK=CCMP]
8.100848: wl1: CTRL-EVENT-CONNECTED
[WM] T11        _wifi_utils_connect_event:834
[WM] T11 _handle_request:1334 state(3) evt(9)
[WM] T11 _handler_on_connecting_state:1011 state(3) evt(9)
[WM] IP address : 192.168.1.34 ----
[WM] T11        _handle_user_cb:1269
[WM] call sta connect success event
log: iotjs_startup_wifi_sta_connected status=0x0
[WM] T11 <-- _handle_request
log: IoT.js app: Starting:
(...)
```

**Comment by rzr** [comment]
@nherriot as you closed 
https://github.com/rzr/webthing-iotjs/issues/2

I guess this one is not reproductible either on your artik055s ?

So please, paste log of current version and then close 
https://github.com/rzr/webthing-iotjs/issues/1
too

Then I'll tag my branch...

If something unexpected happens again, please raise new bugs i will analyse logs.

**Comment by nherriot** [comment]
Testing on the Artik055 board I get the system connecting to WiFi in the lab. I get the following log showing IP address and the device is pingable:

[WM] get IP address 192.168.123.155
[WM] T12        _handle_user_cb:1336
[WM] call sta connect success event
log: iotjs_startup_wifi_sta_connected status=0x0
[WM] T12 <-- _handle_request
log: IoT.js app: Starting:
{ 
  "env": {
    "HOME": "",
    "IOTJS_PATH": "/rom",
    "IOTJS_ENV": "",
    "IOTJS_EXTRA_MODULE_PATH": "/rom/example/iotjs_modules",
    "IOTJS_WORKING_DIR_PATH": ""
  },
  "builtin_modules": {
    "adc": true,
    "assert": true,
    "buffer": true,
    "console": true,
    "dgram": true,
    "dns": true,
    "events": true,
    "fs": true,
    "gpio": true,
    "http": true,
    "http_client": true,
    "http_common": true,
    "http_incoming": true,
    "http_outgoing": true,
    "http_server": true,
    "https": true,
    "i2c": true,
    "iotjs": true,
    "module": true,
    "net": true,
    "pwm": true,
    "spi": true,
    "stream": true,
    "stream_duplex": true,
    "stream_internal": true,
    "stream_readable": true,
    "stream_writable": true,
    "timers": true,
    "tls": true,
    "uart": true,
    "util": true,
    "constants": true,
    "http_parser": true,
    "process": true,
    "tcp": true,
    "udp": true
  },
  "platform": "tizenrt",
  "arch": "arm",
  "version": "1.0.0",
  "iotjs": {
    "board": "artik05x"
  },
  "argv": [
    "iotjs",
    "/rom/example/index.js"
  ],
  "_events": {},
  "exitCode": 0,
  "_exiting": false
}
log: IoT.js app: Loading: /rom/iotjs_modules/webthing-iotjs/example/platform/index.js
log: board: artik05x: Loading
Usage:
iotjs /rom/example/index.js [board] [port]
Try:
curl -H "Accept: application/json" http://localhost:8888

log: board: artik05x: Started
log: GPIO: BlueLed: open: null
log: GPIO: RedLed: open: null
log: GPIO: LeftButton: open: null (null expected)
log: GPIO: RightButton: open: null (null expected)
log: ADC: ADC1: open: null (null expected)
log: ADC: ADC2: open: null (null expected)
log: GPIO: LeftButton: change: true
log: GPIO: RightButton: change: true
log: ADC: ADC1: change: 0%
log: ADC: ADC2: change: 0%



Pinging the device over several minutes on the same WiFi network shows latency in the 100msec range.

Button press latency is in the order of 1-8 seconds. Quite slow for a microcontroller:

TASH>>log: GPIO: RightButton: change: false
log: GPIO: RightButton: change: true
log: GPIO: RightButton: change: false
log: GPIO: RightButton: change: true
log: GPIO: RightButton: change: false
log: GPIO: RightButton: change: true
log: GPIO: LeftButton: change: false
log: GPIO: LeftButton: change: true

I'll close this bug report now.

**Comment by rzr** [comment]
Thanks @nherriot 

Feel free to raise new bug if you see any WiFi failure
please also share full log, (from reboot ...)

Relate-to: https://github.com/Samsung/TizenRT/pull/2319
